Upload Omega Hover Nerf Patch
Knuxfan24/Sonic-06-Mod-Manager-Patches pull request #14
Opened 2022-12-28 17:05 UTC by JotaroPowered

Uploading this patch as a standalone.

2022-12-29 02:04 UTC, HyperBE32 requested changes

2022-12-29 02:04 UTC, HyperBE32 commented on OmegaHoverNerf.mlua
> +Blurb("Limits Omega Hovering")
Change the Blurb field to `Limits Omega's hovering to only a few seconds to prevent exploits.`

2023-01-07 01:03 UTC, JotaroPowered reviewed
Changes look good

2023-01-07 01:05 UTC, HyperBE32 commented
Those aren't changes, you need to commit them yourself.

2023-01-07 01:06 UTC, HyperBE32 commented on Restore Multiplayer Particles.mlua
> +Title("Restore Multiplayer Particles")
Change the Title field to `Fix Multiplayer Particles`

2023-01-07 01:08 UTC, HyperBE32 requested changes

2023-01-07 01:08 UTC, HyperBE32 commented on Restore Multiplayer Particles.mlua
> +Blurb("Adds Particles back to multiplayer")
Change the Blurb field to `Fixes some particles not displaying in multiplayer.`

2023-01-07 01:08 UTC, HyperBE32 commented on Restore Multiplayer Particles.mlua
> +Description("Allows particles to be displayed in multiplayer")
Remove the Description field

2023-01-07 01:46 UTC, merged